version: "2"

volumes:
  web_frontend_node_modules:
  web_frontend_prod_node_modules:

services:
  web-frontend-dev:
    build:
      context: ./
      dockerfile: ./ops/Dockerfile-dev
    tty: true
    mem_limit: 256m
    container_name: "web-frontend-dev"
    working_dir: /app
    environment:
      - NODE_ENV=development
    dns:
     - 1.1.1.1
     - 4.2.2.1
     - 8.8.4.4
    volumes:
     - ./:/app:rw
     - web_frontend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      web-frontend-network:
        aliases:
        - react

  web-frontend-prod:
    build:
      context: ./
      dockerfile: ./ops/Dockerfile
      args:
        - BUILD_FORCE=yes
        - VERSION=0.0.1
        - BUILD_NUMBER=31
        - PORT=3000
        - DATA_GATEWAY=http://host.docker.internal:8733/data-gateway/v1
    tty: true
    environment:
      - NODE_ENV=production
      - DATA_GATEWAY=http://host.docker.internal:8733/data-gateway/v1
    mem_limit: 256m
    container_name: "web-frontend-prod"
    working_dir: /app
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      web-frontend-network:
        aliases:
        - web

networks:
  web-frontend-network:
    driver: bridge
