# Container_name can not scale beyond one container
# Note: Anonymous /app/node_modules volume.
version: "2"

volumes:
  lsr_node_modules:
  lsr_prod_node_modules:

services:
  lsr-dev:
    build:
      context: ./
      dockerfile: ./ops/Dockerfile-dev
    tty: true
    mem_limit: 256m
    container_name: "lsr-dev"
    working_dir: /app
    environment:
      - NODE_ENV=development
    dns:
     - 1.1.1.1
     - 4.2.2.1
     - 8.8.4.4
    volumes:
     - ./:/app:rw
     - lsr_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      lsr-network:
        aliases:
        - react

  lsr-prod:
    build:
      context: ./
      dockerfile: ./ops/Dockerfile
      args:
        - BUILD_FORCE=yes
        - VERSION=0.0.1
        - BUILD_NUMBER=31
        - PORT=3000
        - DATA_GATEWAY=http://host.docker.internal:8733/data-gateway/lsrecord
    tty: true
    environment:
      - NODE_ENV=production
      - DATA_GATEWAY=http://host.docker.internal:8733/data-gateway/lsrecord
    mem_limit: 256m
    container_name: "lsr-prod"
    working_dir: /app
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      lsr-network:
        aliases:
        - web

networks:
  lsr-network:
    driver: bridge
